#!/bin/bash

CURRENTFOLDER=`pwd`
BINFOLDER=$CURRENTFOLDER"/bin/"
MAINJAVA=$CURRENTFOLDER"/src/tv/justin/problems/Prefixer.java"
PARENJAVA=$CURRENTFOLDER"/src/tv/justin/problems/Parentheser.java"
MAINCLASS=$CURRENTFOLDER"/bin/tv/justin/problems/Prefixer.class"

if [ ! -d $BINFOLDER ];
then
   mkdir $BINFOLDER
   echo "Compilation running..."
   javac -d $BINFOLDER $MAINJAVA $PARENJAVA
   echo "Compilation finished."
fi

java -classpath $BINFOLDER tv.justin.problems.Prefixer $*

